
PackageIdentifier: Porrey.VirtualZPLPrinter
PackageVersion: 3.4.0
InstallerType: msi
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/porrey/Virtual-ZPL-Printer/raw/main/Installer/Virtual%20ZPL%20Printer%20Setup.msi
    InstallerSha256: 34F882EB943A1259B87E4E4E0F5F58F2F2EAD73CB20E5BF4E84A6E18B58BB35C
ManifestType: installer
ManifestVersion: 1.6.0
